version: "3.9"

services:
  fake_php:
    image: php:8.2-apache
    container_name: fake_php
    ports:
      - "${PHP_PORT}:80"  # PHP disponible en puerto definido en .env
    volumes:
      - ./fake_site:/var/www/html
    env_file:
      - ./.env
    depends_on:
      - fake_mysql
    restart: unless-stopped
    networks:
      - network1   # red externa Nginx Proxy Manager

  fake_mysql:
    image: mysql:8.0
    container_name: fake_mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_EXTERNAL_PORT}:3306"  # puerto externo de la VPS/local
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - network1   # opcional, para que NPM pueda ver el contenedor si hace falta

networks:
  network1:
    name: ${RED_NOW}   # usamos la red de Nginx Proxy Manager
    external: true
